Move MX record to its own subdomain
chatmail/relay pull request #403
Opened 2024-08-15 12:07 UTC by link2xt

2024-08-15 13:28 UTC, missytake approved these changes

2024-09-02 21:03 UTC, hpk42 commented
changelog entry is missing.

2024-10-30 10:01 UTC, hpk42 requested changes
Please provide a reason for this change.  i can guess but it's not clear to me, sorry. 
Also, would the letsencrypt certs not need to be adapted for "mx.maildomain"?

2024-11-22 17:14 UTC, missytake commented
> Please provide a reason for this change. i can guess but it's not clear to me, sorry. Also, would the letsencrypt certs not need to be adapted for "mx.maildomain"?

One reason is that we can then add proxy VPSs for IMAP+SMTP usage only, but not as MX.

2025-02-16 18:26 UTC, closed without merging